---
name: CI

on:
  pull_request:
    paths-ignore: ["docs/**"]

  push:
    paths-ignore: ["docs/**"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint_test:
    name: Run linting & unittest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install prometheus config validator
        run: make ci
